import os

try:
    train_command = (
        'CUDA_VISIBLE_DEVICES="0,1" fairseq-train /home/krish/content/Hindi_Marathi/wmt22_spm/wmt22_bin '
        '--finetune-from-model /home/krish/content/12b_avg10_chk_2_gpus.pt '
        '--save-dir checkpoint12B '
        '--task translation_multi_simple_epoch '
        '--encoder-normalize-before '
        '--langs "hi,mr" '
        '--lang-pairs "hi-mr" '
        '--max-tokens 1200 '
        '--decoder-normalize-before '
        '--sampling-method temperature '
        '--sampling-temperature 1.5 '
        '--encoder-langtok src '
        '--decoder-langtok '
        '--criterion label_smoothed_cross_entropy '
        '--label-smoothing 0.2 '
        '--optimizer adam '
        '--adam-eps 1e-06 '
        '--adam-betas "(0.9, 0.98)" '
        '--lr-scheduler inverse_sqrt '
        '--lr 3e-05 '
        '--warmup-updates 2500 '
        '--max-update 40000 '
        '--dropout 0.3 '
        '--attention-dropout 0.1 '
        '--weight-decay 0.0 '
        '--update-freq 2 '
        '--save-interval 1 '
        '--save-interval-updates 5000 '
        '--keep-interval-updates 10 '
        '--no-epoch-checkpoints '
        '--seed 222 '
        '--log-format simple '
        '--log-interval 2 '
        '--patience 10 '
        '--arch transformer_wmt_en_de_big_pipeline_parallel '
        '--encoder-layers 24 '
        '--decoder-layers 24 '
        '--encoder-attention-heads 16 '
        '--decoder-attention-heads 16 '
        '--encoder-ffn-embed-dim 16384 '
        '--decoder-ffn-embed-dim 16384 '
        '--decoder-embed-dim 4096 '
        '--encoder-embed-dim 4096 '
        '--num-embedding-chunks 2 '
        '--pipeline-balance "[29,22,1]" '
        '--pipeline-devices "[0,1,0]" '
        '--fp16 --dataset-impl mmap '
        '--pipeline-chunks 1 '
        '--share-decoder-input-output-embed '
        '--share-all-embeddings '
        '--ddp-backend no_c10d '
        '--clip-norm 1.0'
    )
    # Execute command
    os.system(train_command)

except Exception as e:
    print(f"Error: {e}")
